import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import NavBar from "@/components/navbar";
import AuthenticationButton from "@/components/auth/authentication-button";

import { ourFileRouter } from "./api/uploadthing/core";
import "./globals.css";
// import { db } from "@/lib/db";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar>
          <AuthenticationButton />
        </NavBar>
        {/* <NavBar/> */}
        <main className="">
          <NextSSRPlugin
            /**
             * The `extractRouterConfig` will extract **only** the route configs
             * from the router to prevent additional information from being
             * leaked to the client. The data passed to the client is the same
             * as if you were to fetch `/api/uploadthing` directly.
             */
            routerConfig={extractRouterConfig(ourFileRouter)}
          />

          {children}
        </main>
      </body>
    </html>
  );
}
